trainer: 
  max_epochs: &max_epoch 200
  accelerator: 'auto'
  devices: 1
  log_every_n_steps: 10
  
task:
  _target_: ezspeech.task.asr.ASR_ctc_task
  model:
    encoder:
      _target_: ezspeech.models.conformer_asr.Conformer
      d_input: 128
      d_hidden: &d_hidden 512
      num_heads: 8
      num_layers: 12
      depthwise_conv_kernel_size: 31
      vocab_size: 98
      subsampling_num_filter: 256
      subsampling_kernel_size:  3

    criterion:
      _target_: ezspeech.losses.ctc.CTCLoss
      reduction: 'mean'
      zero_infinity: True
    manager:
      optimizer:
        lr: 2e-5
        betas: [ 0.9, 0.999 ]
        eps: 1e-9
        weight_decay: 0.01
      scheduler:
        num_warmup_steps: 4000

  dataset:
    
    trainset:
      _target_: ezspeech.data.asr.ASRDataset
      filepath: /home4/khanhnd/vivos/train.tsv
      vocab_file: ezspeech/resources/vocab.txt
      augmentations:
        feature:
          time_masking:
            _target_: ezspeech.data.augment.time_masking
            time_width: 0.05
            time_masks: 10
            prob: 0.2
          frequency_masking:
            _target_: ezspeech.data.augment.frequency_masking
            time_width: 27
            time_masks: 1
            prob: 0.2
        raw_wav:
          wav_augment:
            _target_: ezspeech.data.augment.wav_augment
            prob: 0.2

    valset:
      _target_: ezspeech.data.asr.ASRDataset
      filepath: /home4/khanhnd/vivos/test.tsv
      vocab_file: ezspeech/resources/vocab.txt
    batch_size: 8

callbacks:
  checkpoint: 
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    # monitor: val_loss
    monitor: step
    filename: 'model-{epoch:02d}-{val_loss:.2f}'
    save_top_k: 3
    save_last: True
    mode: 'max'
    every_n_epochs: 1
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
  swa:
    _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
    swa_epoch_start: 0.8
    swa_lrs: 1e-2
    annealing_epochs: 1

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: log
  name: 'lightning_logs'
  version: test_code1
  

  # val_check_interval: 1  #
