task:
  _target_: ezspeech.tasks.recognition.SpeechRecognitionTask

  dataset:
    vocab: &vocab ezspeech/resource/vocab.txt
    train_ds:
      _target_: ezspeech.modules.dataset.dataset.SpeechRecognitionDataset
      filepaths:
        - /home4/khanhnd/Ezspeech/data/mix.jsonl
      vocab: *vocab
      augmentation:
        # audio_augment:
          # speed_perturbation:
          #   _target_: ezspeech.datas.augment.SpeedPerturbation
          #   orig_freqs: 16000
          #   factors: [0.9, 1.1, 1.0, 1.0, 1.0]

          # pitchshift:
          #   _target_: ezspeech.datas.augment.PitchShift
          #   min_step: -5
          #   max_step: 5
          #   sample_rates: [16000]
          #   probability: 0.2

          # rir_noise:
          #   _target_: ezspeech.datas.augment.ApplyImpulseResponse
          #   rir_filepath_16k: /data/sondd9/noise-16k/RIR.json
          #   second_before_peak: 0.01
          #   second_after_peak: 0.5
          #   probability: 0.2

          # background_noise:
          #   _target_: ezspeech.augment.AddBackgroundNoise
          #   noise_filepath_16k: /data/sondd9/noise-16k/background-noise.json
          #   # noise_filepath_8k: /dataset/8k/noise/background-noise.json
          #   min_snr_db: 0.0
          #   max_snr_db: 30.0
          #   probability: 0.2

        feature_augment:
          freq_masking:
            _target_: ezspeech.modules.dataset.augment.FrequencyMasking
            freq_masks: 1
            freq_width: 27

          time_masking:
            _target_: ezspeech.modules.dataset.augment.TimeMasking
            time_masks: 10
            time_width: 0.05


    val_ds:
      _target_: ezspeech.modules.dataset.dataset.SpeechRecognitionDataset
      filepaths:
        - /home4/khanhnd/Ezspeech/data/test.jsonl

      vocab: *vocab
    loaders:
      batch_size: 4
      num_workers: 8
      pin_memory: false

  model:
    # variables for TDT configs.
    tdt_durations: [0, 1, 2, 3, 4]
    num_tdt_durations: 5
    d_model: &d_model 512
    vocab_size: &vocab_size 1830
    # pretrained_weights: /data/datbt7/checkpoints/asr-offline-60000h.ckpt


    encoder:
      _target_: ezspeech.modules.encoder.squeezeformer.SqueezeFormerEncoder
      input_dim: 128
      d_model: *d_model
      num_layers: 12
      subsampling_factor: 4
      subsampling_num_filters: 256
      subsampling_kernel_size: 3
      attn_num_heads: 8
      attn_group_size: 3
      attn_max_pos_encoding: 10000
      conv_kernel_size: 31
      dropout: 0.1
    decoder:
      _target_: ezspeech.modules.decoder.decoder.CTCDecoder
      input_dim: *d_model
      hidden_dim: *d_model
      output_dim: *vocab_size



    predictor:
      _target_: ezspeech.modules.decoder.rnnt.rnnt.RNNTDecoder
      vocab_size: *vocab_size
      normalization_mode: null # Currently only null is supported for export.
      random_state_sampling: false # Random state sampling: https://arxiv.org/pdf/1910.11455.pdf
      blank_as_pad: true # This flag must be set in order to support exporting of RNNT models + efficient inference.

      prednet:
        pred_hidden: *d_model
        pred_rnn_layers: 1
        t_max: null
        dropout: 0.2

    joint:
      _target_: nemo.collections.asr.modules.RNNTJoint
      log_softmax: null  # 'null' would set it automatically according to CPU/GPU device
      preserve_memory: false  # dramatically slows down training, but might preserve some memory

      # Fuses the computation of prediction net + joint net + loss + WER calculation
      # to be run on sub-batches of size `fused_batch_size`.
      # When this flag is set to true, consider the `batch_size` of *_ds to be just `encoder` batch size.
      # `fused_batch_size` is the actual batch size of the prediction net, joint net and transducer loss.
      # Using small values here will preserve a lot of memory during training, but will make training slower as well.
      # An optimal ratio of fused_batch_size : *_ds.batch_size is 1:1.
      # However, to preserve memory, this ratio can be 1:8 or even 1:16.
      # Extreme case of 1:B (i.e. fused_batch_size=1) should be avoided as training speed would be very slow.
      fuse_loss_wer: true
      fused_batch_size: 16

      jointnet:
        joint_hidden: *d_model
        activation: "relu"
        dropout: 0.2
      num_extra_outputs: ${model.num_tdt_durations}

    criterion:
      _target_: ezspeech.modules.losses.hybrid.HybridRNNT_CTC
        blank: 0
        reduction: mean_batch
        zero_infinity: true
      ctc_weight: 1.0
      rnnt_weight: 1.0

    optimizer:
      lr: 1
      betas: [0.9, 0.999]
      weight_decay: 1e-2
      eps: 1e-9
      foreach: False
      fused: True

    scheduler:
      d_model: *d_model
      warmup_steps: 10000

callbacks:
  lr:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor

  swa:
    _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
    swa_lrs: 1e-6
    swa_epoch_start: 0.8
    annealing_epochs: 1

  cb:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: step
    save_top_k: 3
    save_last: True
    filename: "{epoch}-{val_ctc_loss:.5f}"
    every_n_epochs: 1

loggers:
  tb:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ../lightning_logs/oov
    name: null
    version: testcode

    default_hp_metric: false

trainer:
  max_epochs: 60
  # strategy: ddp
  accelerator: gpu
  devices: [1]
  accumulate_grad_batches: 2
  # detect_anomaly: True
  # precision: 16
  val_check_interval: 0.1